[project]
name = "simple-web-template"
version = "0.1.0"
description = "Simple Web Template"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "python-dotenv>=1.0.1",
]
